### ISSUE TITLE
Crash when hitting mobs with tools made from specific RAA material

### ISSUE THREAD

**Issue by alxpettit** [vampire-studios/Randomly-Adding-Anything-Materials#6] opened 2020-07-12 23:46 UTC
Many of the materials it generated were fine, but when I use one called 'antecalice' for a sword, it results in crashes any time a mob is hit with it. Some examples [here](https://paste.ee/p/Twje0) and [here]( https://paste.ee/p/FgiL6 ). I can upload the world if needed.

**Comment by arthurbambou** [comment] 2020-07-13 10:40
Can you send you material config? It will help debugging.

**Comment by alxpettit** [comment] 2020-07-14 02:24
Um, sure! How do I do that?

**Comment by oliviathevampire** [comment] 2020-07-14 10:36
Are you sure that’s the same config that caused the makerial you talked about yesterday to crash?

**Comment by oliviathevampire** [comment] 2020-07-14 10:37
Can’t seem to find it

**Comment by alxpettit** [comment] 2020-07-14 17:46
I'm pretty sure it's there. It's on line 2985! ^_^

**Comment by oliviathevampire** [comment] 2020-07-16 00:06
ooooooh, I think I might know what the problem is, going to talk with @arthurbambou tomorrow

**Comment by arthurbambou** [comment] 2020-07-16 13:19
Closed by [f8ca0f4](https://github.com/vampire-studios/Randomly-Adding-Anything-Materials/commit/f8ca0f412f8bc1f6a479c20a0fd319ab519279eb)

**Closed by arthurbambou** 2020-07-16 13:19 UTC
